name: Near binary builder
run-name: Near binary builder
on: [push]
permissions:
  contents: write

env:
  NEAR_VERSION: 1.36.0

jobs:
  build-near:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "near/nearcore"
          ref: "${{ env.NEAR_VERSION }}"
      - run: "sudo apt install binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev cmake gcc g++ protobuf-compiler libssl-dev pkg-config clang llvm cargo"

