name: Near binary builder
run-name: Near binary builder
on: [push]
permissions:
  contents: write

env:
  NEAR_VERSION: 1.37.3

jobs:
  build-near:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "near/nearcore"
          ref: "${{ env.NEAR_VERSION }}"
      - run: "sudo apt update"
      - run: "sudo apt install binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev cmake gcc g++ protobuf-compiler libssl-dev pkg-config clang llvm cargo"
      - run: |
          if ! command -v rustup &> /dev/null ; then
            curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --default-toolchain none -y
            echo "${CARGO_HOME:-$HOME/.cargo}/bin" >> $GITHUB_PATH
          fi
      - run: "make neard"
      - run: tar -czvf neard-${{ env.NEAR_VERSION}}.tgz -C target/release/ neard
      - uses: actions/upload-artifact@v3
        with:
          name: "neard-${{ env.NEAR_VERSION }}.tgz"
          path: "neard-${{ env.NEAR_VERSION }}.tgz"
  release:
    runs-on: ubuntu-latest
    needs: [build-near]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: "neard-${{ env.NEAR_VERSION }}.tgz"
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            neard-${{ env.NEAR_VERSION }}.tgz
          tag_name: "neard-${{ env.NEAR_VERSION }}"

